### PR TITLE
Add good comments for a cleaner code #8

### PR DESCRIPTION
**Pull request by Samunee**
Add good comments for a cleaner code #8 

In this commit/pull request: 
- Added cleaner comments for all files within the ./src directory.
- Comments are placed before each class definition, detailing their syntax and compiled format.

### CODE REVIEW

**Review by rudransh61 — APPROVED** [review]
I think , it is fine ,
Thanks for contributing !! and joining us !!

**Comment by rudransh61** [comment]
You can star the repo and share it with others !!!

**Comment by rudransh61** [comment]
RUN the shell file to update the final file for production
`./build.sh`

**Comment by rudransh61** [comment]
Then it will be ready to merge

**Comment by rudransh61** [comment]
You can check `./CODE STRUCTURE.md`
To learn how this bash file works

**Comment by Samunee** [comment]
okay, thank you for giving me the opportunity to contribute 😄

**Comment by Samunee** [comment]
This has been approved, is there any chance I can become a contributor to contribute to this project?

**Pull request merged**
